### ISSUE TITLE
Why "Use italic text for constants"?

### ISSUE THREAD

**Issue by timakro** [jeffkreeftmeijer/vim-dim#2]
As I understand from your blog post this colorscheme is supposed to resemble the Vim default color scheme as closely as possible using ANSI colors only.

Does the Vim default color scheme use italic text for constants? If not, why this change?

**Comment by jeffkreeftmeijer** [comment]
Hey @timakro,

Dim’s goal isn’t to resemble Vim’s default as closely as possible, but rather to have a color scheme that only uses ANSI colours, so it's customisable through terminal profiles.

I've added italics for constants because I thought it was a nice way to differentiate from the rest of the code without only relying on color while I was playing around with more monochrome color schemes. I liked the way they looked, so I moved those to Dim.

That said, I'm open to discuss this, if this is something other users have issues with as well.

**Comment by timakro** [comment]
Yes, the number one goal is to use ANSI colors only of course. And actually you're right, it says nowhere that this tries to resemble Vim's default closely. There are tweaks like the gray line numbers, and I like most of them. So "Default IMproved" puts it perfectly.

So regarding the italic constants it's up to preference then. In my console font italic looks very pronounced, not great when there is a lot of it like string literals. I do think using italic for something as abundant as literals is pretty divisive. For my part I change this back in my .vimrc after loading the color scheme.

On that note another thing I change there is the colors for the spell checker. Dim highlights spelling mistakes (SpellBad) in green as opposed to Vim's default which is red. I assume that goes against the intuition of most people.

**Comment by jeffkreeftmeijer** [comment]
Alright, let’s revert this for now. I’m not attached to this at all, just thought it looked nice. Thanks for bringing this up, I didn’t think it would really affect anyone, and added it because I thought it looked nice in my setup:

<img width="682" alt="Screenshot 2020-12-26 at 23 38 17" src="https://user-images.githubusercontent.com/43621/103160300-70bc6b00-47d3-11eb-8edc-cb3b1b421646.png">

I’d love to see what it looks like on yours. :)

Oh, and could you create a pull request with `SpellBad` change? I’d be happy to merge that in.

**Comment by timakro** [comment]
![image](https://user-images.githubusercontent.com/8438790/103161721-50e27280-47e6-11eb-87f1-6ead7d320de9.png)

Here's what it looks for me. :)

Just can't get used to the slanted numbers.

**Comment by timakro** [comment]
Hi @jeffkreeftmeijer, I got interested in light color schemes and remembered your screenshot. Would you care to share what color scheme you're using in the picture? I really like the bright and vibrant colors. :)

**Comment by jeffkreeftmeijer** [comment]
Hey Tim,

That’s https://github.com/jeffkreeftmeijer/darklight.terminal on macOS’ Terminal.app. If you’re using a different terminal emulator, the colors might not come out the same way as in that screenshot, as Terminal.app does some color mixing with the background.

I’ve been meaning to publish the exact color values somewhere, so they can be used in other terminals. I’ll take another shot at that if you’d like to use it in something other than Terminal.app.
